"""empty message

Revision ID: 0155f897cb42
Revises: 14ce0b3f3edf
Create Date: 2023-10-06 10:00:10.065245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0155f897cb42'
down_revision = '14ce0b3f3edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notificacaoPersonal', schema=None) as batch_op:
        batch_op.drop_constraint('tb_notificacaoPersonal_personal_id_fkey', type_='foreignkey')
        batch_op.drop_column('personal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notificacaoPersonal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tb_notificacaoPersonal_personal_id_fkey', 'tb_personalTrainer', ['personal_id'], ['usuario_id'])

    # ### end Alembic commands ###
