"""empty message

Revision ID: 1b1d2ea398cb
Revises: 4715f07b2b0c
Create Date: 2023-09-24 18:53:05.847643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1d2ea398cb'
down_revision = '4715f07b2b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_personalTrainer', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_personalTrainer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
