"""empty message

Revision ID: 25119e7b6952
Revises: eab6e5d8d1e5
Create Date: 2023-11-15 22:08:53.297995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25119e7b6952'
down_revision = 'eab6e5d8d1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_assinaturas')
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    op.create_table('tb_assinaturas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_AssinaturaStripe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intervalo', postgresql.INTERVAL(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_fim_teste', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plano_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], name='tb_assinaturas_atleta_id_fkey'),
    sa.ForeignKeyConstraint(['plano_id'], ['tb_planos.id'], name='tb_assinaturas_plano_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tb_assinaturas_pkey')
    )
    # ### end Alembic commands ###
