"""Possiblidade de rejeitar o atleta pelo personal

Revision ID: 2b6f2a18226f
Revises: 9b7930ad19b4
Create Date: 2023-10-11 11:01:54.441164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6f2a18226f'
down_revision = '9b7930ad19b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_rejeitado',
    sa.Column('notificacao_id', sa.Integer(), nullable=True),
    sa.Column('personal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notificacao_id'], ['tb_notificacaoPersonal.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['tb_personalTrainer.usuario_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_rejeitado')
    # ### end Alembic commands ###
