"""empty message

Revision ID: 2f948f8ff0ee
Revises: 6afa96313f00
Create Date: 2023-11-20 09:37:26.779021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f948f8ff0ee'
down_revision = '6afa96313f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.drop_constraint('tb_assinaturas_atleta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_atleta', ['atleta_id'], ['usuario_id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.alter_column('statusPagamento',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('tb_cartaoCredito', schema=None) as batch_op:
        batch_op.drop_constraint('tb_cartaoCredito_atleta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_atleta', ['atleta_id'], ['usuario_id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    with op.batch_alter_table('tb_cartaoCredito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_cartaoCredito_atleta_id_fkey', 'tb_atleta', ['atleta_id'], ['usuario_id'])

    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.alter_column('statusPagamento',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_assinaturas_atleta_id_fkey', 'tb_atleta', ['atleta_id'], ['usuario_id'])

    # ### end Alembic commands ###
