"""empty message

Revision ID: 310937d22012
Revises: fd44aab92217
Create Date: 2023-10-03 18:00:07.741708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310937d22012'
down_revision = 'fd44aab92217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.drop_constraint('tb_atleta_personal_trainer_id_fkey', type_='foreignkey')
        batch_op.drop_column('personal_trainer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_trainer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tb_atleta_personal_trainer_id_fkey', 'tb_personalTrainer', ['personal_trainer_id'], ['usuario_id'])

    # ### end Alembic commands ###
