"""Novo atributo do stripe no atleta

Revision ID: 3590556ec5d6
Revises: 6ebc524decd9
Create Date: 2023-11-10 17:24:04.865962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3590556ec5d6'
down_revision = '6ebc524decd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.drop_column('stripe_id')

    # ### end Alembic commands ###
