"""Add Nutricionista

Revision ID: 3a4208e862db
Revises: 1b1d2ea398cb
Create Date: 2023-09-25 09:08:48.347633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4208e862db'
down_revision = '1b1d2ea398cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_nutricionista',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('crn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('crn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_nutricionista')
    # ### end Alembic commands ###
