"""empty message

Revision ID: 3f0e5af2a35d
Revises: 1e37a85de16a
Create Date: 2023-12-05 15:49:47.869505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0e5af2a35d'
down_revision = '1e37a85de16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_cardapio', schema=None) as batch_op:
        batch_op.drop_constraint('tb_cardapio_nutricionista_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_nutricionista', ['nutricionista'], ['usuario_id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    with op.batch_alter_table('tb_cardapio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_cardapio_nutricionista_fkey', 'tb_nutricionista', ['nutricionista'], ['usuario_id'])

    # ### end Alembic commands ###
