"""add tabela de notificacao de nutricionista

Revision ID: 4075c9962315
Revises: 2b6f2a18226f
Create Date: 2023-10-11 12:05:44.489171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4075c9962315'
down_revision = '2b6f2a18226f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_notificacaoNutricionista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('solicitacao', sa.Boolean(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('nutricionista_rejeitado',
    sa.Column('notificacao_id', sa.Integer(), nullable=True),
    sa.Column('personal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notificacao_id'], ['tb_notificacaoNutricionista.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['tb_nutricionista.usuario_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutricionista_rejeitado')
    op.drop_table('tb_notificacaoNutricionista')
    # ### end Alembic commands ###
