"""Add notification Personal Trainer

Revision ID: 421c19d54fc2
Revises: be8df7e5e9c4
Create Date: 2023-09-30 12:51:05.870916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421c19d54fc2'
down_revision = 'be8df7e5e9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_notificacaoPersonal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('solicitacao', sa.Boolean(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['tb_personalTrainer.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_notificacaoPersonal')
    # ### end Alembic commands ###
