"""Add Administrador

Revision ID: 44030d8e9f1b
Revises: 3a4208e862db
Create Date: 2023-09-25 10:58:51.957514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44030d8e9f1b'
down_revision = '3a4208e862db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_administrador',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_administrador')
    # ### end Alembic commands ###
