"""empty message

Revision ID: 469916e16968
Revises: c2fd4dab368d
Create Date: 2023-11-16 17:45:07.094469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '469916e16968'
down_revision = 'c2fd4dab368d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
