"""Add model Personal Trainer

Revision ID: 4715f07b2b0c
Revises: 931f31f7d58d
Create Date: 2023-09-23 12:53:16.096328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4715f07b2b0c'
down_revision = '931f31f7d58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_personalTrainer',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cref', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_personalTrainer')
    # ### end Alembic commands ###
