"""empty message

Revision ID: 47baa41ad88c
Revises: f24e6f233995
Create Date: 2023-11-02 16:53:54.612920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47baa41ad88c'
down_revision = 'f24e6f233995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_tabelaTreino', schema=None) as batch_op:
        batch_op.alter_column('observacoes',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_tabelaTreino', schema=None) as batch_op:
        batch_op.alter_column('observacoes',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
