"""empty message

Revision ID: 4d342b87862b
Revises: 9f78a645fe8c
Create Date: 2023-11-12 18:26:13.870711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d342b87862b'
down_revision = '9f78a645fe8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cartaoCredito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cartaoCredito', sa.Integer(), nullable=False),
    sa.Column('bandeira', sa.String(), nullable=False),
    sa.Column('mesVencimento', sa.String(), nullable=False),
    sa.Column('anoVencimento', sa.String(), nullable=False),
    sa.Column('finalCartao', sa.String(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    op.drop_table('tb_cartaoCredito')
    # ### end Alembic commands ###
