"""empty message

Revision ID: 5010ce1fc377
Revises: 3f0e5af2a35d
Create Date: 2023-12-05 17:25:19.096970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5010ce1fc377'
down_revision = '3f0e5af2a35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
