"""empty message

Revision ID: 504cc990307a
Revises: 5efa6c179299
Create Date: 2023-11-08 09:27:01.235598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504cc990307a'
down_revision = '5efa6c179299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
