"""empty message

Revision ID: 5efa6c179299
Revises: f77fb994c05f
Create Date: 2023-11-05 13:49:47.567285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efa6c179299'
down_revision = 'f77fb994c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ingrediente', schema=None) as batch_op:
        batch_op.drop_constraint('tb_ingrediente_refeicao_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_refeicao', ['refeicao'], ['id'])

    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_refeicao_por_dia', ['diaSemana', 'tipoRefeicao', 'cardapio'])
        batch_op.drop_constraint('tb_refeicao_cardapio_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_cardapio', ['cardapio'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_refeicao_cardapio_fkey', 'tb_tabelaTreino', ['cardapio'], ['id'])
        batch_op.drop_constraint('unique_refeicao_por_dia', type_='unique')

    with op.batch_alter_table('tb_ingrediente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_ingrediente_refeicao_fkey', 'tb_tabelaTreino', ['refeicao'], ['id'])

    # ### end Alembic commands ###
