"""empty message

Revision ID: 5f24896c96a3
Revises: 794057b2de09
Create Date: 2023-11-10 17:12:16.540279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f24896c96a3'
down_revision = '794057b2de09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_cardapio', schema=None) as batch_op:
        batch_op.drop_constraint('tb_cardapio_atleta_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_atleta', ['atleta'], ['usuario_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_cardapio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_cardapio_atleta_fkey', 'tb_atleta', ['atleta'], ['usuario_id'])

    # ### end Alembic commands ###
