"""empty message

Revision ID: 6322b07c1566
Revises: 
Create Date: 2023-11-23 00:20:38.805371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6322b07c1566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ProductStripe', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_PlanoStripe', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('intervalo', sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['tb_produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_AssinaturaStripe', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('intervalo', sa.Enum('day', 'week', 'month', 'year', name='intervalo_planoAssinatura'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('data_inicio_teste', sa.DateTime(), nullable=True),
    sa.Column('data_fim_teste', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plano_id'], ['tb_planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id')
    )
    op.create_table('tb_cartaoCredito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cartaoCredito', sa.String(), nullable=False),
    sa.Column('nomeTitular', sa.String(), nullable=False),
    sa.Column('bandeira', sa.String(), nullable=False),
    sa.Column('mesVencimento', sa.String(), nullable=False),
    sa.Column('anoVencimento', sa.String(), nullable=False),
    sa.Column('finalCartao', sa.String(), nullable=False),
    sa.Column('pagamentoPadrao', sa.String(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produto')
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.alter_column('statusPagamento',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.alter_column('statusPagamento',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_ProductStripe', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='produto_pkey')
    )
    op.drop_table('tb_cartaoCredito')
    op.drop_table('tb_assinaturas')
    op.drop_table('tb_planos')
    op.drop_table('tb_produtos')
    # ### end Alembic commands ###
