"""empty message

Revision ID: 6ebc524decd9
Revises: 5f24896c96a3
Create Date: 2023-11-10 17:17:42.511181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebc524decd9'
down_revision = '5f24896c96a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ingrediente', schema=None) as batch_op:
        batch_op.drop_constraint('tb_ingrediente_refeicao_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_refeicao', ['refeicao'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.drop_constraint('tb_refeicao_cardapio_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_cardapio', ['cardapio'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_refeicao_cardapio_fkey', 'tb_cardapio', ['cardapio'], ['id'])

    with op.batch_alter_table('tb_ingrediente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_ingrediente_refeicao_fkey', 'tb_refeicao', ['refeicao'], ['id'])

    # ### end Alembic commands ###
