"""empty message

Revision ID: 6f85306743a3
Revises: f095a679f6bf
Create Date: 2023-11-11 18:44:42.373718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f85306743a3'
down_revision = 'f095a679f6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
