"""empty message

Revision ID: 794057b2de09
Revises: 292e2af96407
Create Date: 2023-11-10 17:08:47.624635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794057b2de09'
down_revision = '292e2af96407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_exercicioAtleta', schema=None) as batch_op:
        batch_op.drop_constraint('tb_exercicioAtleta_tabelaTreino_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_tabelaTreino', ['tabelaTreino'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_exercicioAtleta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_exercicioAtleta_tabelaTreino_fkey', 'tb_tabelaTreino', ['tabelaTreino'], ['id'])

    # ### end Alembic commands ###
