"""Initial commit

Revision ID: 87f895556c50
Revises: 
Create Date: 2023-11-11 16:46:14.433509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f895556c50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_produtos', schema=None) as batch_op:
        batch_op.alter_column('id_ProductStripe',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_produtos', schema=None) as batch_op:
        batch_op.alter_column('id_ProductStripe',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
