"""First Commit

Revision ID: 931f31f7d58d
Revises: 
Create Date: 2023-09-23 12:03:38.930917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931f31f7d58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_atleta',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('massaMagra', sa.Float(), nullable=True),
    sa.Column('massaGorda', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('statusPagamento', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_atleta')
    op.drop_table('tb_usuario')
    # ### end Alembic commands ###
