"""First Commit

Revision ID: 9b7930ad19b4
Revises: 
Create Date: 2023-10-08 19:35:41.101240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7930ad19b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('exp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_administrador',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_imgUsuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fotoPerfil', sa.LargeBinary(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_nutricionista',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('crn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('crn')
    )
    op.create_table('tb_personalTrainer',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cref', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('cref')
    )
    op.create_table('tb_atleta',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('massaMagra', sa.Float(), nullable=True),
    sa.Column('massaGorda', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('statusPagamento', sa.Boolean(), nullable=False),
    sa.Column('personal_trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personal_trainer_id'], ['tb_personalTrainer.usuario_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('tb_notificacaoPersonal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('solicitacao', sa.Boolean(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_notificacaoPersonal')
    op.drop_table('tb_atleta')
    op.drop_table('tb_personalTrainer')
    op.drop_table('tb_nutricionista')
    op.drop_table('tb_imgUsuarios')
    op.drop_table('tb_administrador')
    op.drop_table('tb_usuario')
    op.drop_table('tb_blacklist')
    # ### end Alembic commands ###
