"""empty message

Revision ID: 9f78a645fe8c
Revises: 0a644a6ff92a
Create Date: 2023-11-12 18:21:42.989807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f78a645fe8c'
down_revision = '0a644a6ff92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cartaoCredito')
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    op.create_table('tb_cartaoCredito',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"tb_cartaoCredito_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_cartaoCredito', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bandeira', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mesVencimento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anoVencimento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finalCartao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['tb_atleta.usuario_id'], name='tb_cartaoCredito_atleta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tb_cartaoCredito_pkey')
    )
    # ### end Alembic commands ###
