"""empty message

Revision ID: a02a08f81f88
Revises: ee2c18869edb
Create Date: 2023-11-16 11:49:17.554544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a02a08f81f88'
down_revision = 'ee2c18869edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_fim', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.drop_column('data_fim')

    # ### end Alembic commands ###
