"""Add imagem dos usuarios

Revision ID: aa5f057426b4
Revises: 0155f897cb42
Create Date: 2023-10-06 12:22:36.789032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5f057426b4'
down_revision = '0155f897cb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_imgUsuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fotoPerfil', sa.LargeBinary(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_imgUsuarios')
    # ### end Alembic commands ###
