"""Update NotificacaoPersonal

Revision ID: bb67e1d5e734
Revises: 421c19d54fc2
Create Date: 2023-10-03 12:09:33.041876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb67e1d5e734'
down_revision = '421c19d54fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notificacaoPersonal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atleta_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['atleta_id'])
        batch_op.create_foreign_key(None, 'tb_atleta', ['atleta_id'], ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notificacaoPersonal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('atleta_id')

    # ### end Alembic commands ###
