"""empty message

Revision ID: c2fd4dab368d
Revises: 41134188c64d
Create Date: 2023-11-16 13:58:21.082061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2fd4dab368d'
down_revision = '41134188c64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_planos', schema=None) as batch_op:
        batch_op.alter_column('intervalo',
               existing_type=sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)

    with op.batch_alter_table('tb_assinaturas', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
