"""add tabela de planos do nutri workout

Revision ID: d7324518c667
Revises: 87f895556c50
Create Date: 2023-11-11 18:33:44.794687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7324518c667'
down_revision = '87f895556c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_PlanoStripe', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('intervalo', sa.Enum('day', 'week', 'month', 'year', name='intervalo_plano'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['tb_produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_planos')
    # ### end Alembic commands ###
