"""novo campo no atleta de status do imc

Revision ID: e3d8010f797d
Revises: e5cc83c8729e
Create Date: 2023-11-04 13:02:39.968227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d8010f797d'
down_revision = 'e5cc83c8729e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statusImc', sa.String(), nullable=True))

    with op.batch_alter_table('tb_exercicioAtleta', schema=None) as batch_op:
        batch_op.alter_column('tabelaTreino',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_exercicioAtleta', schema=None) as batch_op:
        batch_op.alter_column('tabelaTreino',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.drop_column('statusImc')

    # ### end Alembic commands ###
