"""Upgrade tabela de treino e nova tabela exercicio atleta

Revision ID: e5cc83c8729e
Revises: 47baa41ad88c
Create Date: 2023-11-03 11:25:59.558682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cc83c8729e'
down_revision = '47baa41ad88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_exercicioAtleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musculoTrabalhado', sa.String(), nullable=False),
    sa.Column('nomeExercicio', sa.String(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('repeticao', sa.Integer(), nullable=False),
    sa.Column('descanso', sa.Integer(), nullable=False),
    sa.Column('unidadeDescanso', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('tabelaTreino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tabelaTreino'], ['tb_tabelaTreino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_tabelaTreino', schema=None) as batch_op:
        batch_op.drop_column('kg')
        batch_op.drop_column('series')
        batch_op.drop_column('unidadeDescanso')
        batch_op.drop_column('nomeExercicio')
        batch_op.drop_column('repeticao')
        batch_op.drop_column('musculoTrabalhado')
        batch_op.drop_column('descanso')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_tabelaTreino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('descanso', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('musculoTrabalhado', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('repeticao', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nomeExercicio', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('unidadeDescanso', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('series', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kg', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('tb_exercicioAtleta')
    # ### end Alembic commands ###
