"""empty message

Revision ID: e9984505b6f2
Revises: 504cc990307a
Create Date: 2023-11-08 09:27:11.140203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9984505b6f2'
down_revision = '504cc990307a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_refeicao', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
