"""add tabela de treinno

Revision ID: f24e6f233995
Revises: 1e0500509c70
Create Date: 2023-11-02 15:43:12.625475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24e6f233995'
down_revision = '1e0500509c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_tabelaTreino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semanaInicio', sa.Date(), nullable=False),
    sa.Column('semanaFim', sa.Date(), nullable=False),
    sa.Column('musculoTrabalhado', sa.String(), nullable=False),
    sa.Column('nomeExercicio', sa.String(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('repeticao', sa.Integer(), nullable=False),
    sa.Column('descanso', sa.Integer(), nullable=False),
    sa.Column('unidadeDescanso', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=False),
    sa.Column('atleta', sa.Integer(), nullable=True),
    sa.Column('personal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta'], ['tb_atleta.usuario_id'], ),
    sa.ForeignKeyConstraint(['personal'], ['tb_personalTrainer.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_tabelaTreino')
    # ### end Alembic commands ###
