"""novos campos cardapio, refeicao e ingredinete

Revision ID: f77fb994c05f
Revises: e3d8010f797d
Create Date: 2023-11-05 13:10:15.573200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77fb994c05f'
down_revision = 'e3d8010f797d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('atleta', sa.Integer(), nullable=True),
    sa.Column('nutricionista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta'], ['tb_atleta.usuario_id'], ),
    sa.ForeignKeyConstraint(['nutricionista'], ['tb_nutricionista.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta')
    )
    op.create_table('tb_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('quantidade', sa.String(), nullable=False),
    sa.Column('refeicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refeicao'], ['tb_tabelaTreino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('diaSemana', sa.Enum('segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name="dia_da_semana"), nullable=False),
    sa.Column('tipoRefeicao', sa.Enum('cafe_manha', 'lanche_manha', 'almoço', 'lanche_tarde', 'janta', 'lanche_noite', name="tipo_refeicao"), nullable=False),
    sa.Column('cardapio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio'], ['tb_tabelaTreino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_refeicao')
    op.drop_table('tb_ingrediente')
    op.drop_table('tb_cardapio')
    # ### end Alembic commands ###
