"""empty message

Revision ID: fbaeab06ab51
Revises: 4075c9962315
Create Date: 2023-10-16 10:44:06.348934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaeab06ab51'
down_revision = '4075c9962315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutricionista_rejeitado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutricionista_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('nutricionista_rejeitado_personal_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_nutricionista', ['nutricionista_id'], ['usuario_id'])
        batch_op.drop_column('personal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutricionista_rejeitado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nutricionista_rejeitado_personal_id_fkey', 'tb_nutricionista', ['personal_id'], ['usuario_id'])
        batch_op.drop_column('nutricionista_id')

    # ### end Alembic commands ###
