"""Add associação entre personal trainer e o atleta

Revision ID: fd44aab92217
Revises: bb67e1d5e734
Create Date: 2023-10-03 14:03:19.489127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd44aab92217'
down_revision = 'bb67e1d5e734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_trainer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tb_personalTrainer', ['personal_trainer_id'], ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_atleta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personal_trainer_id')

    # ### end Alembic commands ###
